# Uso: docker compose -f docker-compose.dev.yaml up -d

services:
  renovabit-postgres:
    container_name: renovabit-postgres
    image: postgres:18.4
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-renovabit}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - renovabit

  # renovabit-api:
  #   container_name: renovabit-api
  #   build:
  #     context: .
  #     dockerfile: apps/api/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env.api
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     renovabit-postgres:
  #       condition: service_healthy
  #   networks:
  #     - renovabit

  # renovabit-admin:
  #   container_name: renovabit-admin
  #   build:
  #     context: .
  #     dockerfile: apps/admin/Dockerfile
  #     args:
  #       - VITE_API_URL=http://renovabit-api:3001
  #   restart: unless-stopped
  #   ports:
  #     - "3002:3002"
  #   environment:
  #     - VITE_API_URL=http://renovabit-api:3001
  #   depends_on:
  #     - renovabit-api
  #   networks:
  #     - renovabit

networks:
  renovabit:
    name: renovabit
    driver: bridge
